// Class automatically generated by Dev-C++ New Class wizard

#include "link.h" // class's header file

Link::Link(Node &A, Node &B, const double massden, const double resilence, const double maxDeltaLength)
: A(A), B(B), maxDeltaLength(maxDeltaLength) {
    length = originalLength = A.pos.distans(B.pos); //d³ugo¶æ
    deltaLength = 0.0;
    mass = massden * originalLength;           //masa
    alfa = resilence / originalLength;        //wsp. alfa
}

/*Link::Link(const Link& toCopy)
: mass(toCopy.mass), alfa(toCopy.alfa), length(toCopy.length),
  originalLength(toCopy.originalLength), deltaLength(toCopy.deltaLength),
  maxDeltaLength(toCopy.maxDeltaLength), A(toCopy.A), B(toCopy.B) {};*/


//nie zmieniaæ masy node w destruktorze i konstruktorze bo s¹ one wywo³ywane w doœæ przypadkowych momentach w programie!!!
