// Class automatically generated by Dev-C++ New Class wizard

#include "node.h" // class's header file

// class constructor
//node::node()
//{
	// insert your code here
//}

// class destructor
Node::~Node()
{
	// insert your code here
}

