// Class automatically generated by Dev-C++ New Class wizard

#ifndef TIMER_H
#define TIMER_H

#include <ctime>	//clock_t, clock(), CLOCKS_PER_SEC, time_t, time
#include <iostream>
#include <iomanip>  

/**
 * Zegarek, mierzy odstêpy czasowe z dok³adnoœci¹ do 0.001 sec.
 * Powy¿ej 1/2h precyzja maleje do 1sec.
 */
class Timer {
	
    clock_t start_clock;
    time_t start_time;

	public:
		
		///Tworzy nowy zegar i go startuje.
		Timer(): start_clock(clock()), start_time(time(0)) {};
        
        ///Restartuje zegar.
        void restart() {
        	start_clock = clock();
        	start_time  = time(0);
        }
        
        /**
         * Restartuje zegar.
         * @return ile sekund up³yne³o od poprzedniego restartu zegara.
         */
        double intervalSec() {
        	double result = getSec();
        	restart();
        	return result;
        }
        
        ///@return ile sekund up³yne³o od poprzedniego restartu zegara.
        double getSec() const {
        	time_t acc_sec = time(0) - start_time;
			if (acc_sec < 3600)	//mamy dok³adny czas?
				return double(clock() - start_clock) / double(CLOCKS_PER_SEC);
			else
				return double(acc_sec);
        }
        
        friend std::ostream& operator<<(std::ostream& os, const Timer& t) {
        	os << std::setprecision(2) << std::setiosflags(std::ios::fixed) << t.getSec();
  			return os;
        }
};


#endif // TIMER_H

