// Class automatically generated by Dev-C++ New Class wizard

#include "camera2d.h" // class's header file

void Camera2d::set() const {
    double sx = (double)w / zoom / 2.0;
    double sy = (double)h / zoom / 2.0;
    glViewport(0, 0, w, h);
    glMatrixMode(GL_PROJECTION);  // Select The Projection Matrix
    glLoadIdentity();             // Reset The Projection Matrix
    gluOrtho2D(x - sx, x + sx, y - sy, y + sy);
}

void Camera2d::resize(int width, int height) {
    w = width;
    h = height;
    set();
}

// class destructor
Camera2d::~Camera2d()
{
	// insert your code here
}

